package seg.g33.Entitites;

public class Obstacle {

    /**
     * Name of the obstacle
     */
    private String name;

    /**
     * Obstacle Height
     */
    private double height;

    /**
     * Distance from the centerpoint of the runway
     */
    private Double centerDistance;

    /**
     * Distance from the left of the runway
     */
    private Double leftDistance;

    /**
     * Distance from the right of the runway
     */
    private Double rightDistance;

    /**
     * Constructor
     */
    public Obstacle(String name, Double height, Double center, Double left, Double right) {
        this.name = name;
        this.height = height;
        this.centerDistance = center;
        this.leftDistance = left;
        this.rightDistance = right;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getHeight() {
        return height;
    }

    public void setHeight(double height) {
        this.height = height;
    }

    public Double getCenterDistance() {
        return centerDistance;
    }

    public void setCenterDistance(Double centerDistance) {
        this.centerDistance = centerDistance;
    }

    public Double getLeftDistance() {
        return leftDistance;
    }

    public void setLeftDistance(Double leftDistance) {
        this.leftDistance = leftDistance;
    }

    public Double getRightDistance() {
        return rightDistance;
    }

    public void setRightDistance(Double rightDistance) {
        this.rightDistance = rightDistance;
    }

    /**
     * Autogenerated toString override for Obstacle class
     * Used for debugging purposes.
     */
    @Override
    public String toString() {
        return "Obstacle{" +
                "name='" + name + '\'' +
                ", height=" + height +
                ", centerDistance=" + centerDistance +
                ", leftDistance=" + leftDistance +
                ", rightDistance=" + rightDistance +
                '}';
    }
}
