package seg.g33.Entitites;

public class Obstacle {

    /**
     * Name of the obstacle
     */
    private String name;

    /**
     * Obstacle Height
     */
    private double height;

    /**
     * Distance from the center-line of the runway
     */
    private Double centerDistance;

    /**
     * Distance from the left of the runway
     */
    private Double leftDistance;

    /**
     * Distance from the right of the runway
     */
    private Double rightDistance;

    /**
     * Constructor
     */
    public Obstacle(String name, Double height, Double center, Double left, Double right) {
        this.name = name;
        this.height = height;
        this.centerDistance = center;
        this.leftDistance = left;
        this.rightDistance = right;
    }

    /**
     * Getter for the name of the obstacle
     * @return the name of the obstacle
     */
    public String getName() {
        return name;
    }

    /**
     * Setter for the name of the obstacle
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter method to get the height of the obstacle
     * @return
     */
    public double getHeight() {
        return height;
    }

    /**
     * Setter method to set the height of the obstacle
     * @param height sets the height of an obstacle
     */
    public void setHeight(double height) {
        this.height = height;
    }

    /**
     * Getter method to get the distance to the center of the runway from the obstacle
     * @return distance from the obstacle to the center of the runway
     */
    public Double getCenterDistance() {
        return centerDistance;
    }

    /**
     * Setter method to set the distance of the obstacle from the center of the runway
     * @param centerDistance distance of the obstacle from the center of the runway
     */
    public void setCenterDistance(Double centerDistance) {
        this.centerDistance = centerDistance;
    }

    /**
     * Getter method to get the distance to the left of the runway from the obstacle
     * @return distance from the obstacle to the left of the runway
     */
    public Double getLeftDistance() {
        return leftDistance;
    }

    /**
     * Setter method to set the distance of the obstacle from the left of the runway
     * @param leftDistance distance of the obstacle from the left of the runway
     */
    public void setLeftDistance(Double leftDistance) {
        this.leftDistance = leftDistance;
    }

    /**
     * Getter method to get the distance to the right of the runway from the obstacle
     * @return distance from the obstacle to the right of the runway
     */
    public Double getRightDistance() {
        return rightDistance;
    }

    /**
     * Setter method to set the distance of the obstacle from the right of the runway
     * @param rightDistance distance of the obstacle from the right of the runway
     */
    public void setRightDistance(Double rightDistance) {
        this.rightDistance = rightDistance;
    }

    /**
     * Autogenerated toString override for Obstacle class
     * Used for debugging purposes.
     */
    @Override
    public String toString() {
        return "Obstacle{" +
                "name='" + name + '\'' +
                "\n\t- height=" + height +
                "\n\t- centerDistance=" + centerDistance +
                "\n\t- leftDistance=" + leftDistance +
                "\n\t- rightDistance=" + rightDistance +
                "\n}";
    }
}
